### ISSUE TITLE
lecture 1 .Symbol lookup error .

### ISSUE THREAD

**Issue by ZhangChi-fd** [amazerobot/AerialManipulator#6]
尝试运行xacro模型时出现这个报错
试过了重装mavros 和 按步骤重新进行px4环境配属
还是出现这个报错
![0b7f08f603a026739486950719ba939](https://user-images.githubusercontent.com/76096282/154504340-ae728cc3-e793-4917-9bb8-0c5fdd974c0c.jpg)

**Comment by hilinxinhui** [comment]
你好，我们无法复现你的问题，以下建议供参考：
- 请具体说明执行的指令
- 请将错误信息复制粘贴到issue中
- 可以参考 https://github.com/amazerobot/AerialManipulator/issues/2 ，在相应目录下查看`libmavros.so`的指向，将输出贴到issue中

**Comment by ZhangChi-fd** [comment]
执行的指令：roslaunch px4 posix_sitl_xacro.launch
报错信息：/opt/ros/melodic/lib/mavros/mavros_node: symbol lookup error: /opt/ros/melodic/lib/[libmavros.so](http://libmavros.so/): undefined symbol: _ZN7mavconn16MAVConnInterface19open_url_no_connectENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEhh
我看了一下 和https://github.com/amazerobot/AerialManipulator/issues/2 好像不是一个问题

**Comment by hilinxinhui** [comment]
我表达的是，`libmavros.so`应该是一个符号链接，这里的问题应该来自于该符号链接指向了错误的/不存在的文件，可以参考 #2 中的检查和解决方案，至少向我们展示你执行`ls -l`指令的结果。

**Comment by ZhangChi-fd** [comment]
问题已解决 
问题应该是系统的配置问题 检查和环境配置文档操作无误以后
根据https://github.com/mavlink/mavros/blob/master/mavros/README.md#installation 里面源码编译的步骤安装mavros 
之后要注意重新配置环境变量

**Comment by andsoonme** [comment]
您好 我也遇到了相同问题 请问有具体的解决步骤吗

**Comment by andsoonme** [comment]
已经解决
sudo apt update
sudo apt upgrade
